export const katexTagWhiteList = {
  math: [],
  annotation: [],
  semantics: [],
  mtext: [],
  mn: [],
  mo: [],
  mi: [],
  mspace: [],
  mover: [],
  munder: [],
  munderover: [],
  msup: [],
  msub: [],
  msubsup: [],
  mfrac: [],
  mroot: [],
  msqrt: [],
  mtable: [],
  mtr: [],
  mtd: [],
  mlabeledtr: [],
  mrow: [],
  menclose: [],
  mstyle: [],
  mpadded: [],
  mphantom: [],
  mglyph: [],
};

export const katexAttrWhiteList = [
  'mathcolor',
  'mathbackground',
  'mathsize',
  'mathvariant',
  'mathfamily',
  'mathweight',
  'mathstyle',
  'mathdisplay',
];
