// This file is auto generated by build/build-entry.js
import Component from './base-editor.vue';
import { getGlobal, setGlobal } from '@/utils/global';

const version = '1.0.7';

const install = (Vue) => {
  Vue.component(Component.name, Component);
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

Component.version = version;
Component.install = install;
Component.useTheme = function (themeConfig) {
  setGlobal('theme', themeConfig);

  if (themeConfig.plugins) this.usePlugins(themeConfig.plugins);
};
Component.usePlugins = function (plugins) {
  setGlobal('plugins', [...(getGlobal('plugins') || []), ...plugins]);
};

export default Component;
